// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student_registration.Data;

#nullable disable

namespace student_registration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241217023719_One to Many Relationship")]
    partial class OnetoManyRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("student_registration.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bungoma"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Iten"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kandara"
                        });
                });

            modelBuilder.Entity("student_registration.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNo")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnologyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            IdNo = 55555555,
                            Name = "Andrew Kimwetich",
                            Phone = 765383853,
                            Registration = "BIT/041/21",
                            School = "Science",
                            TechnologyId = 1
                        });
                });

            modelBuilder.Entity("student_registration.Models.Technology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = ".NET Developer",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("student_registration.Models.Location", b =>
                {
                    b.HasOne("student_registration.Models.Student", "Student")
                        .WithMany("Locations")
                        .HasForeignKey("StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("student_registration.Models.Technology", b =>
                {
                    b.HasOne("student_registration.Models.Student", "Student")
                        .WithOne("Technology")
                        .HasForeignKey("student_registration.Models.Technology", "StudentId");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("student_registration.Models.Student", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Technology");
                });
#pragma warning restore 612, 618
        }
    }
}
